configure_time:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            integration: "nuvo_serial"
            model: "Grand Concerto NV-I8G"
    datetime:
      required: true
      selector:
        datetime:

set_source_display:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            integration: "nuvo_serial"
            model: "Source"
    line1:
      required: false
      selector:
        text:
    line2:
      required: false
      selector:
        text:
    line3:
      required: false
      selector:
        text:
    line4:
      required: false
      selector:
        text:

snapshot:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"
          multiple: true

restore:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"
          multiple: true

party_on:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

party_off:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

simulate_play_pause_button:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

simulate_prev_button:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

simulate_next_button:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"
